### ISSUE TITLE
Printing setting is not correct / perfect.

### ISSUE THREAD

**Issue by Jeff-Tian** [sonnyhcl/beamerthemefdu#3]
![image](https://user-images.githubusercontent.com/3367820/95279596-af522180-0885-11eb-881c-13e438895ee2.png)

**Comment by sonnyhcl** [comment]
~~Printer setting seems no issue in my side. Please double check whether you have specificly set your printer settings for your browser~~. 
![image](https://user-images.githubusercontent.com/10840522/115261050-e1620b80-a165-11eb-9826-1a360ac7cd0c.png)

Oh I made a mistake. Once you choose printer destination as a printer, the default scale size is not fit for A4 size. 
A quick workaround is to setting scale as "Fit to printable area". @Jeff-Tian
![image](https://user-images.githubusercontent.com/10840522/115261720-72d17d80-a166-11eb-8d48-98a025acd596.png)
